version: "3.1"

services:
  portainer:
    image: portainer/portainer:latest
    container_name: portainer
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - /etc/dockerapp/portainer/data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8000:8000
      - 9443:9443
    restart: unless-stopped

  jellyfin:
    image: nyanmisaka/jellyfin
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
    devices:
      - /dev/dri/card0:/dev/dri/card0
      - /dev/dri/renderD128:/dev/dri/renderD128
    ports:
      - 8096:8096
    volumes:
      - /etc/dockerapp/jellyfin/config:/config
      - /etc/dockerapp/jellyfin/cache:/cache
      - /titan/space/media:/media
    restart: unless-stopped

  prowlarr:
    image: linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
    volumes:
      - /etc/dockerapp/prowlarr:/config
    ports:
      - 9696:9696
    restart: unless-stopped

  resync:
    image: linuxserver/resilio-sync:latest
    container_name: resync
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
    volumes:
      - ./ban/hosts:/etc/hosts:ro
      - /etc/dockerapp/resync:/config
      - /titan/cloud/resync/downloads:/downloads
      - /titan/cloud/resync/sync:/sync

    network_mode: host
    #ports:
    #  - 8888:8888
    #  - 55555:55555
    restart: unless-stopped

  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - /etc/nginx:/etc/nginx
    network_mode: host
    restart: unless-stopped
 
  xunlei:
    image: cnk3x/xunlei:latest
    container_name: xunlei
    hostname: pve
    privileged: true
    network_mode: host
      # host网络，默认端口 2345
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
      - XL_WEB_PORT=2345
    volumes:
      - /etc/dockerapp/xunlei:/xunlei/data
      - /titan/space/downloads:/xunlei/downloads
    restart: unless-stopped
